blank_issues_enabled: false

#contact_links:
#  - name: 🌐 Ir al sitio web
#    url: https://wow-patagonia.win
#    about: Página oficial del servidor. Descargá el cliente y encontrá información general.
#
#  - name: 💬 Soporte y comunidad (Discord)
#    url: https://discord.gg/H8NN8bxP5F
#    about: Soporte, consultas generales y comunicación con la comunidad.
